GET http://localhost:3000/api/v1/club/admin/33/members
Authorization: Bearer [token]
content-type: application/json

###

DELETE http://localhost:3000/api/v1/club/admin/31/members/48
Authorization: Bearer [token]
content-type: application/json

