GET http://localhost:3000/api/v1/club
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

###

GET http://localhost:3000/api/v1/club/approved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

###

GET http://localhost:3000/api/v1/club/not-approved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

###

GET http://localhost:3000/api/v1/club/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

###

POST http://localhost:3000/api/v1/club
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

{
    "title": "UW HipHop",
    "description": "This is a cool club that you should join.",
    "membership_fee": 12,
    "categories": [1],
    "position": "VP of Marketing"
}

###

PUT http://localhost:3000/api/v1/club/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json

{
    "title": "UW Dhamaka",
    "description": "This is a very cool club that you should join.",
    "membership_fee": 10,
    "categories": [1],
    "is_approved": true 
}

###

DELETE http://localhost:3000/api/v1/club/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhMzNwYXRpbEB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IlBhc3N3b3JkMSQiLCJmaXJzdF9uYW1lIjoiQWJoaW5pdCIsImxhc3RfbmFtZSI6IlBhdGlsIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTA3NTE4OH0.Po9_nFMszCfDBA4TZC3nle9lN--0isuhf4mifj9d_0Y
content-type: application/json
