
GET http://localhost:3000/api/v1/friend
Authorization: Bearer [token]
content-type: application/json

###

GET http://localhost:3000/api/v1/friend/requests
Authorization: Bearer [token]
content-type: application/json

###

POST http://localhost:3000/api/v1/friend
Authorization: Bearer [token]
content-type: application/json

{
    "email": "m5afshar@uwaterloo.ca"
}

###

PUT http://localhost:3000/api/v1/friend/approve-request
Authorization: Bearer [token]
content-type: application/json

{
    "friend_id": 3
}

###

DELETE http://localhost:3000/api/v1/friend/3
Authorization: Bearer [token]
content-type: application/json
