POST http://localhost:3000/api/v1/user/login
content-type: application/json

{
    "email": "a33patil@uwaterloo.ca",
    "password": "Password1$"
}

###

GET http://localhost:3000/api/v1/user/decode-token-test-endpoint
Authorization: Bearer [token]
