POST http://localhost:3000/api/v1/user/login
content-type: application/json

{
    "email": "test@uwaterloo.ca",
    "password": "jfkdfkj"
}

###

GET http://localhost:3000/api/v1/user/val
Authorization: Bearer tokenhere
