
POST http://localhost:3000/api/v1/user/registration-email-verification
content-type: application/json

{
    "email": "a33patil@uwaterloo.ca"
}

###

POST http://localhost:3000/api/v1/user/register
content-type: application/json

{
    "email": "a33patil@uwaterloo.ca",
		"password": "Password1$",
		"first_name": "Abhinit",
		"last_name": "Patil",
		"code": 846027
}