PUT http://localhost:3000/api/v1/share/club
content-type: application/json
Authorization: Bearer [token]

{
    "destinationUserId": 48,
		"clubId": 34
}

###

GET http://localhost:3000/api/v1/share
content-type: application/json
Authorization: Bearer [token]
