PUT http://localhost:3000/api/v1/share/club
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiY2x1YndhdC5hZG1pbkB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IiQyYiQxMiRSY1VxMmtWemZHRDIzTFdCWFlGSFFPeVQuaWZUS0dFSVRXUmpvZ3ZwMUdwTGxrRVVSWUhWMiIsImZpcnN0X25hbWUiOiJBcHBsaWNhdGlvbiIsImxhc3RfbmFtZSI6IkFkbWluIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTg1Njk2M30.yK-yaCY8OwNKoG6SbQju7CuM4HAfYxxfY7XT077TNmI

{
    "destinationUserId": 48,
		"clubId": 34
}

###

GET http://localhost:3000/api/v1/share
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsImVtYWlsIjoiazQ0Z3VwdGFAdXdhdGVybG9vLmNhIiwicGFzc3dvcmQiOiIkMmIkMTIkSzdGdTBjLjZEWFhYNTBmMFVGeGoyT0J5d0pVZE9pcHRSckkuUDkuWk54bzZDVURWTk1HYVciLCJmaXJzdF9uYW1lIjoiS2VzaGF2IiwibGFzdF9uYW1lIjoiR3VwdGEiLCJhZG1pbl9mbGFnIjpmYWxzZSwiaWF0IjoxNzA5OTAyNDczfQ.GvPw0n47REpGnO7NzTXwxzO3VwLJ6evGi368twRF2bw
