GET http://localhost:3000/api/v1/user/41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiY2x1YndhdC5hZG1pbkB1d2F0ZXJsb28uY2EiLCJwYXNzd29yZCI6IiQyYiQxMiRSY1VxMmtWemZHRDIzTFdCWFlGSFFPeVQuaWZUS0dFSVRXUmpvZ3ZwMUdwTGxrRVVSWUhWMiIsImZpcnN0X25hbWUiOiJBcHBsaWNhdGlvbiIsImxhc3RfbmFtZSI6IkFkbWluIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcxMDEwMjkxMX0.u0FJlBcXtSBo77S3r9hEyAa_Ge0cQzh7nkoNIP0Zoqg

###

DELETE http://localhost:3000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImVtYWlsIjoidGVzdHRlc3R0ZXN0QHV3YXRlcmxvby5jYSIsInBhc3N3b3JkIjoiJDJiJDEyJHVlYVgzMy5KMmdLWjZaSThLcGtLN3VuZTlOQlFNbUVxcWIxZWxkVGRDa2J0dWxWTXRPUE15IiwiZmlyc3RfbmFtZSI6IksiLCJsYXN0X25hbWUiOiJHIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcxMDI3NzMzMX0.3CQ7ixaXG4JZGvBaNnM8Apf79qvY2ZUl1q1yH-GuHt0
