GET http://localhost:3000/api/v1/interest/user/all
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYTM2M2d1cHRAdXdhdGVybG9vLmNhIiwicGFzc3dvcmQiOiIkMmIkMTAkSFg0RVkvRjhYNy8xT2lTeHJWSVd3T29wQkNKR2dQeDJNaUtIV1BMSlhwN1VHQWw1cTNYbU8iLCJmaXJzdF9uYW1lIjoiQWJoaW5hdiIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTI0MDQ1MH0.QQRkvnmZJafUxsK9o0G402UyGdgb3WyCY_JjY-MbiXw

###

GET http://localhost:3000/api/v1/interest/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYTM2M2d1cHRAdXdhdGVybG9vLmNhIiwicGFzc3dvcmQiOiIkMmIkMTAkSFg0RVkvRjhYNy8xT2lTeHJWSVd3T29wQkNKR2dQeDJNaUtIV1BMSlhwN1VHQWw1cTNYbU8iLCJmaXJzdF9uYW1lIjoiQWJoaW5hdiIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTI0MDQ1MH0.QQRkvnmZJafUxsK9o0G402UyGdgb3WyCY_JjY-MbiXw

###

PUT http://localhost:3000/api/v1/interest/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYTM2M2d1cHRAdXdhdGVybG9vLmNhIiwicGFzc3dvcmQiOiIkMmIkMTAkSFg0RVkvRjhYNy8xT2lTeHJWSVd3T29wQkNKR2dQeDJNaUtIV1BMSlhwN1VHQWw1cTNYbU8iLCJmaXJzdF9uYW1lIjoiQWJoaW5hdiIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiYWRtaW5fZmxhZyI6ZmFsc2UsImlhdCI6MTcwOTI0MDQ1MH0.QQRkvnmZJafUxsK9o0G402UyGdgb3WyCY_JjY-MbiXw

{
  "faculty": 9,
  "ethnicity": 17,
  "religion": 29,
  "program": 64,
  "hobbies": [51, 45, 56]
}